// ISO 3166-1 numeric → alpha-2 mapping (usado com world-atlas topojson)
export const ISO_NUMERIC_TO_ALPHA2: Record<string, string> = {
  "4": "AF", "8": "AL", "12": "DZ", "20": "AD", "24": "AO", "28": "AG",
  "31": "AZ", "32": "AR", "36": "AU", "40": "AT", "44": "BS", "48": "BH",
  "50": "BD", "51": "AM", "52": "BB", "56": "BE", "64": "BT", "68": "BO",
  "70": "BA", "72": "BW", "76": "BR", "84": "BZ", "90": "SB", "96": "BN",
  "100": "BG", "104": "MM", "108": "BI", "112": "BY", "116": "KH", "120": "CM",
  "124": "CA", "132": "CV", "140": "CF", "144": "LK", "148": "TD", "152": "CL",
  "156": "CN", "170": "CO", "174": "KM", "178": "CG", "180": "CD", "188": "CR",
  "191": "HR", "192": "CU", "196": "CY", "203": "CZ", "204": "BJ", "208": "DK",
  "212": "DM", "214": "DO", "218": "EC", "222": "SV", "226": "GQ", "231": "ET",
  "232": "ER", "233": "EE", "242": "FJ", "246": "FI", "250": "FR", "262": "DJ",
  "266": "GA", "268": "GE", "270": "GM", "276": "DE", "288": "GH", "296": "KI",
  "300": "GR", "308": "GD", "320": "GT", "324": "GN", "328": "GY", "332": "HT",
  "336": "VA", "340": "HN", "348": "HU", "352": "IS", "356": "IN", "360": "ID",
  "364": "IR", "368": "IQ", "372": "IE", "376": "IL", "380": "IT", "384": "CI",
  "388": "JM", "392": "JP", "398": "KZ", "400": "JO", "404": "KE", "408": "KP",
  "410": "KR", "414": "KW", "417": "KG", "418": "LA", "422": "LB", "426": "LS",
  "428": "LV", "430": "LR", "434": "LY", "438": "LI", "440": "LT", "442": "LU",
  "450": "MG", "454": "MW", "458": "MY", "462": "MV", "466": "ML", "470": "MT",
  "478": "MR", "480": "MU", "484": "MX", "492": "MC", "496": "MN", "498": "MD",
  "499": "ME", "504": "MA", "508": "MZ", "512": "OM", "516": "NA", "520": "NR",
  "524": "NP", "528": "NL", "548": "VU", "554": "NZ", "558": "NI", "562": "NE",
  "566": "NG", "578": "NO", "583": "FM", "584": "MH", "585": "PW", "586": "PK",
  "591": "PA", "598": "PG", "600": "PY", "604": "PE", "608": "PH", "616": "PL",
  "620": "PT", "624": "GW", "626": "TL", "634": "QA", "642": "RO", "643": "RU",
  "646": "RW", "659": "KN", "662": "LC", "670": "VC", "674": "SM", "678": "ST",
  "682": "SA", "686": "SN", "688": "RS", "690": "SC", "694": "SL", "703": "SK",
  "704": "VN", "705": "SI", "706": "SO", "710": "ZA", "716": "ZW", "724": "ES",
  "728": "SS", "729": "SD", "740": "SR", "748": "SZ", "752": "SE", "756": "CH",
  "760": "SY", "762": "TJ", "764": "TH", "768": "TG", "776": "TO", "780": "TT",
  "788": "TN", "792": "TR", "795": "TM", "800": "UG", "804": "UA", "807": "MK",
  "818": "EG", "826": "GB", "840": "US", "854": "BF", "858": "UY", "860": "UZ",
  "862": "VE", "882": "WS", "887": "YE", "894": "ZM",
}

// Nome do país em português
export const ALPHA2_TO_NAME: Record<string, string> = {
  AF: "Afeganistão", AL: "Albânia", DZ: "Argélia", AD: "Andorra", AO: "Angola",
  AG: "Antígua e Barbuda", AZ: "Azerbaijão", AR: "Argentina", AU: "Austrália",
  AT: "Áustria", BS: "Bahamas", BH: "Barein", BD: "Bangladesh", AM: "Armênia",
  BB: "Barbados", BE: "Bélgica", BT: "Butão", BO: "Bolívia", BA: "Bósnia",
  BW: "Botsuana", BR: "Brasil", BZ: "Belize", SB: "Ilhas Salomão", BN: "Brunei",
  BG: "Bulgária", MM: "Mianmar", BI: "Burundi", BY: "Bielorrússia", KH: "Camboja",
  CM: "Camarões", CA: "Canadá", CV: "Cabo Verde", CF: "Rep. Centro-Africana",
  LK: "Sri Lanka", TD: "Chade", CL: "Chile", CN: "China", CO: "Colômbia",
  KM: "Comores", CG: "Congo", CD: "Rep. Dem. do Congo", CR: "Costa Rica",
  HR: "Croácia", CU: "Cuba", CY: "Chipre", CZ: "República Tcheca", BJ: "Benin",
  DK: "Dinamarca", DM: "Dominica", DO: "Rep. Dominicana", EC: "Equador",
  SV: "El Salvador", GQ: "Guiné Equatorial", ET: "Etiópia", ER: "Eritreia",
  EE: "Estônia", FJ: "Fiji", FI: "Finlândia", FR: "França", DJ: "Djibuti",
  GA: "Gabão", GE: "Geórgia", GM: "Gâmbia", DE: "Alemanha", GH: "Gana",
  KI: "Quiribati", GR: "Grécia", GD: "Granada", GT: "Guatemala", GN: "Guiné",
  GY: "Guiana", HT: "Haiti", VA: "Vaticano", HN: "Honduras", HU: "Hungria",
  IS: "Islândia", IN: "Índia", ID: "Indonésia", IR: "Irã", IQ: "Iraque",
  IE: "Irlanda", IL: "Israel", IT: "Itália", CI: "Costa do Marfim", JM: "Jamaica",
  JP: "Japão", KZ: "Cazaquistão", JO: "Jordânia", KE: "Quênia", KP: "Coreia do Norte",
  KR: "Coreia do Sul", KW: "Kuwait", KG: "Quirguistão", LA: "Laos", LB: "Líbano",
  LS: "Lesoto", LV: "Letônia", LR: "Libéria", LY: "Líbia", LI: "Liechtenstein",
  LT: "Lituânia", LU: "Luxemburgo", MG: "Madagascar", MW: "Malawi", MY: "Malásia",
  MV: "Maldivas", ML: "Mali", MT: "Malta", MR: "Mauritânia", MU: "Maurício",
  MX: "México", MC: "Mônaco", MN: "Mongólia", MD: "Moldávia", ME: "Montenegro",
  MA: "Marrocos", MZ: "Moçambique", OM: "Omã", NA: "Namíbia", NR: "Nauru",
  NP: "Nepal", NL: "Holanda", VU: "Vanuatu", NZ: "Nova Zelândia", NI: "Nicarágua",
  NE: "Níger", NG: "Nigéria", NO: "Noruega", FM: "Micronésia", MH: "Ilhas Marshall",
  PW: "Palau", PK: "Paquistão", PA: "Panamá", PG: "Papua Nova Guiné", PY: "Paraguai",
  PE: "Peru", PH: "Filipinas", PL: "Polônia", PT: "Portugal", GW: "Guiné-Bissau",
  TL: "Timor-Leste", QA: "Catar", RO: "Romênia", RU: "Rússia", RW: "Ruanda",
  KN: "São Cristóvão e Névis", LC: "Santa Lúcia", VC: "São Vicente e Granadinas",
  SM: "San Marino", ST: "São Tomé e Príncipe", SA: "Arábia Saudita", SN: "Senegal",
  RS: "Sérvia", SC: "Seicheles", SL: "Serra Leoa", SK: "Eslováquia", VN: "Vietnã",
  SI: "Eslovênia", SO: "Somália", ZA: "África do Sul", ZW: "Zimbábue", ES: "Espanha",
  SS: "Sudão do Sul", SD: "Sudão", SR: "Suriname", SZ: "Essuatíni", SE: "Suécia",
  CH: "Suíça", SY: "Síria", TJ: "Tajiquistão", TH: "Tailândia", TG: "Togo",
  TO: "Tonga", TT: "Trinidad e Tobago", TN: "Tunísia", TR: "Turquia", TM: "Turcomenistão",
  UG: "Uganda", UA: "Ucrânia", MK: "Macedônia do Norte", EG: "Egito", GB: "Reino Unido",
  US: "Estados Unidos", BF: "Burkina Faso", UY: "Uruguai", UZ: "Uzbequistão",
  VE: "Venezuela", WS: "Samoa", YE: "Iêmen", ZM: "Zâmbia",
}

// Continente por alpha-2
export const ALPHA2_TO_CONTINENT: Record<string, string> = {
  // África
  DZ: "África", AO: "África", BJ: "África", BW: "África", BF: "África", BI: "África",
  CM: "África", CV: "África", CF: "África", TD: "África", KM: "África", CG: "África",
  CD: "África", CI: "África", DJ: "África", EG: "África", GQ: "África", ER: "África",
  ET: "África", GA: "África", GM: "África", GH: "África", GN: "África", GW: "África",
  KE: "África", LS: "África", LR: "África", LY: "África", MG: "África", MW: "África",
  ML: "África", MR: "África", MU: "África", MA: "África", MZ: "África", NA: "África",
  NE: "África", NG: "África", RW: "África", ST: "África", SN: "África", SC: "África",
  SL: "África", SO: "África", ZA: "África", SS: "África", SD: "África", SZ: "África",
  TG: "África", TN: "África", UG: "África", ZM: "África", ZW: "África",
  // Ásia
  AF: "Ásia", AM: "Ásia", AZ: "Ásia", BH: "Ásia", BD: "Ásia", BT: "Ásia",
  BN: "Ásia", KH: "Ásia", CN: "Ásia", GE: "Ásia", IN: "Ásia", ID: "Ásia",
  IR: "Ásia", IQ: "Ásia", IL: "Ásia", JP: "Ásia", JO: "Ásia", KZ: "Ásia",
  KW: "Ásia", KG: "Ásia", LA: "Ásia", LB: "Ásia", MY: "Ásia", MV: "Ásia",
  MN: "Ásia", MM: "Ásia", NP: "Ásia", KP: "Ásia", KR: "Ásia", OM: "Ásia",
  PK: "Ásia", PH: "Ásia", QA: "Ásia", SA: "Ásia", SG: "Ásia", LK: "Ásia",
  SY: "Ásia", TJ: "Ásia", TH: "Ásia", TL: "Ásia", TR: "Ásia", TM: "Ásia",
  AE: "Ásia", UZ: "Ásia", VN: "Ásia", YE: "Ásia",
  // Europa
  AL: "Europa", AD: "Europa", AT: "Europa", BY: "Europa", BE: "Europa", BA: "Europa",
  BG: "Europa", HR: "Europa", CY: "Europa", CZ: "Europa", DK: "Europa", EE: "Europa",
  FI: "Europa", FR: "Europa", DE: "Europa", GR: "Europa", HU: "Europa", IS: "Europa",
  IE: "Europa", IT: "Europa", LV: "Europa", LI: "Europa", LT: "Europa", LU: "Europa",
  MT: "Europa", MD: "Europa", MC: "Europa", ME: "Europa", NL: "Europa", MK: "Europa",
  NO: "Europa", PL: "Europa", PT: "Europa", RO: "Europa", RU: "Europa", SM: "Europa",
  RS: "Europa", SK: "Europa", SI: "Europa", ES: "Europa", SE: "Europa", CH: "Europa",
  UA: "Europa", GB: "Europa", VA: "Europa",
  // Oceania
  AU: "Oceania", FJ: "Oceania", KI: "Oceania", MH: "Oceania", FM: "Oceania",
  NR: "Oceania", NZ: "Oceania", PW: "Oceania", PG: "Oceania", WS: "Oceania",
  SB: "Oceania", TO: "Oceania", VU: "Oceania",
  // América do Norte
  AG: "América do Norte", BS: "América do Norte", BB: "América do Norte",
  BZ: "América do Norte", CA: "América do Norte", CR: "América do Norte",
  CU: "América do Norte", DM: "América do Norte", DO: "América do Norte",
  SV: "América do Norte", GD: "América do Norte", GT: "América do Norte",
  HT: "América do Norte", HN: "América do Norte", JM: "América do Norte",
  MX: "América do Norte", NI: "América do Norte", PA: "América do Norte",
  KN: "América do Norte", LC: "América do Norte", VC: "América do Norte",
  TT: "América do Norte", US: "América do Norte",
  // América do Sul
  AR: "América do Sul", BO: "América do Sul", BR: "América do Sul",
  CL: "América do Sul", CO: "América do Sul", EC: "América do Sul",
  GY: "América do Sul", PY: "América do Sul", PE: "América do Sul",
  SR: "América do Sul", UY: "América do Sul", VE: "América do Sul",
}

// Aeroporto IATA → alpha-2 (para recomendações baseadas em buscas)
export const IATA_TO_ALPHA2: Record<string, string> = {
  // Brasil
  GRU: "BR", CGH: "BR", GIG: "BR", BSB: "BR", SSA: "BR", FOR: "BR",
  REC: "BR", POA: "BR", CWB: "BR", CNF: "BR", MAO: "BR", BEL: "BR",
  // EUA
  JFK: "US", EWR: "US", LGA: "US", LAX: "US", ORD: "US", ATL: "US",
  DFW: "US", SFO: "US", MIA: "US", BOS: "US", SEA: "US", MCO: "US",
  DEN: "US", LAS: "US", PHX: "US", IAH: "US", IAD: "US", DCA: "US",
  // Europa
  LHR: "GB", LGW: "GB", MAN: "GB", EDI: "GB",
  CDG: "FR", ORY: "FR", NCE: "FR",
  FRA: "DE", MUC: "DE", DUS: "DE", TXL: "DE", BER: "DE",
  MAD: "ES", BCN: "ES", AGP: "ES", PMI: "ES",
  FCO: "IT", MXP: "IT", VCE: "IT", NAP: "IT",
  LIS: "PT", OPO: "PT", FAO: "PT",
  AMS: "NL", ZRH: "CH", GVA: "CH", VIE: "AT", BRU: "BE",
  CPH: "DK", ARN: "SE", OSL: "NO", HEL: "FI",
  WAW: "PL", PRG: "CZ", BUD: "HU", OTP: "RO",
  ATH: "GR", IST: "TR", SAW: "TR", ADB: "TR",
  // América do Sul
  EZE: "AR", AEP: "AR", COR: "AR", SCL: "CL",
  BOG: "CO", MDE: "CO", LIM: "PE", UIO: "EC", GYE: "EC",
  ASU: "PY", MVD: "UY", CCS: "VE",
  GUA: "GT", SJO: "CR", MGA: "NI", TGU: "HN", SAL: "SV",
  // México e América Central
  MEX: "MX", CUN: "MX", GDL: "MX", MTY: "MX", SJD: "MX",
  // Caribe
  HAV: "CU", SDQ: "DO", PUJ: "DO",
  // Canadá
  YYZ: "CA", YVR: "CA", YUL: "CA", YYC: "CA",
  // Oriente Médio
  DXB: "AE", AUH: "AE", SHJ: "AE", DOH: "QA",
  RUH: "SA", JED: "SA", MED: "SA", KWI: "KW",
  BAH: "BH", MCT: "OM", AMM: "JO", BEY: "LB", TLV: "IL",
  CAI: "EG", HRG: "EG", SSH: "EG",
  // Ásia
  NRT: "JP", HND: "JP", KIX: "JP", NGO: "JP",
  ICN: "KR", GMP: "KR",
  PEK: "CN", PVG: "CN", CAN: "CN", SZX: "CN",
  SIN: "SG", BKK: "TH", DMK: "TH", HKT: "TH",
  KUL: "MY", LGK: "MY", PEN: "MY",
  CGK: "ID", DPS: "ID", SUB: "ID",
  MNL: "PH", CEB: "PH",
  SGN: "VN", HAN: "VN",
  DEL: "IN", BOM: "IN", MAA: "IN", BLR: "IN", CCU: "IN",
  DAC: "BD", CMB: "LK", KTM: "NP",
  // África
  JNB: "ZA", CPT: "ZA", DUR: "ZA",
  CMN: "MA", RAK: "MA", TUN: "TN", ALG: "DZ",
  ADD: "ET", NBO: "KE", MBA: "KE",
  LOS: "NG", ABV: "NG", ACC: "GH", ABJ: "CI",
  DKR: "SN", MRU: "MU", SEZ: "SC",
  // Oceania
  SYD: "AU", MEL: "AU", BNE: "AU", PER: "AU", ADL: "AU",
  AKL: "NZ", WLG: "NZ", NAN: "FJ",
}

export const TOTAL_COUNTRIES = 195
