export const AIRLINE_NAME_MAP = {
    'latam': 'LATAM Airlines', 'latam airlines': 'LATAM Airlines',
    'latam airlines brasil': 'LATAM Airlines', 'tam': 'LATAM Airlines', 'tam linhas aéreas': 'LATAM Airlines',
    'gol': 'GOL Linhas Aéreas', 'gol linhas aereas': 'GOL Linhas Aéreas', 'gol linhas aéreas': 'GOL Linhas Aéreas',
    'gol transportes aéreos': 'GOL Linhas Aéreas',
    'azul': 'Azul Linhas Aéreas', 'azul linhas aereas': 'Azul Linhas Aéreas', 'azul linhas aéreas': 'Azul Linhas Aéreas',
    'azul linhas aéreas brasileiras': 'Azul Linhas Aéreas', 'azul brazilian airlines': 'Azul Linhas Aéreas',
    'copa': 'Copa Airlines', 'copa airlines': 'Copa Airlines',
    'avianca': 'Avianca', 'avianca brasil': 'Avianca',
    'american': 'American Airlines', 'american airlines': 'American Airlines',
    'united': 'United Airlines', 'united airlines': 'United Airlines',
    'delta': 'Delta Air Lines', 'delta air lines': 'Delta Air Lines', 'delta airlines': 'Delta Air Lines',
    'alaska': 'Alaska Airlines', 'alaska airlines': 'Alaska Airlines',
    'jetblue': 'JetBlue', 'jetblue airways': 'JetBlue',
    'southwest': 'Southwest Airlines', 'southwest airlines': 'Southwest Airlines',
    'spirit': 'Spirit Airlines', 'spirit airlines': 'Spirit Airlines',
    'frontier': 'Frontier Airlines', 'frontier airlines': 'Frontier Airlines',
    'air france': 'Air France',
    'klm': 'KLM', 'klm royal dutch airlines': 'KLM',
    'lufthansa': 'Lufthansa',
    'tap': 'TAP Air Portugal', 'tap air portugal': 'TAP Air Portugal', 'tap portugal': 'TAP Air Portugal',
    'iberia': 'Iberia', 'iberia express': 'Iberia',
    'british airways': 'British Airways', 'ba': 'British Airways',
    'swiss': 'Swiss', 'swiss international air lines': 'Swiss', 'swiss air lines': 'Swiss',
    'austrian': 'Austrian Airlines', 'austrian airlines': 'Austrian Airlines',
    'sas': 'SAS', 'scandinavian airlines': 'SAS',
    'finnair': 'Finnair',
    'ryanair': 'Ryanair',
    'easyjet': 'easyJet', 'easy jet': 'easyJet',
    'wizzair': 'Wizz Air', 'wizz air': 'Wizz Air',
    'virgin atlantic': 'Virgin Atlantic',
    'ita airways': 'ITA Airways', 'ita': 'ITA Airways', 'alitalia': 'ITA Airways',
    'air europa': 'Air Europa',
    'emirates': 'Emirates',
    'qatar airways': 'Qatar Airways', 'qatar': 'Qatar Airways',
    'turkish airlines': 'Turkish Airlines', 'turkish': 'Turkish Airlines', 'thy': 'Turkish Airlines',
    'ethiopian': 'Ethiopian Airlines', 'ethiopian airlines': 'Ethiopian Airlines',
    'south african airways': 'South African Airways', 'saa': 'South African Airways',
    'kenya airways': 'Kenya Airways',
    'aeromexico': 'Aeromexico', 'aeroméxico': 'Aeromexico',
    'aerolineas argentinas': 'Aerolíneas Argentinas', 'aerolíneas argentinas': 'Aerolíneas Argentinas',
    'air canada': 'Air Canada',
    'westjet': 'WestJet',
    'singapore airlines': 'Singapore Airlines', 'singapore': 'Singapore Airlines',
    'cathay pacific': 'Cathay Pacific', 'cathay': 'Cathay Pacific',
    'japan airlines': 'Japan Airlines', 'jal': 'Japan Airlines',
    'ana': 'ANA', 'all nippon airways': 'ANA',
    'korean air': 'Korean Air',
    'air china': 'Air China',
    'china southern': 'China Southern',
    'china eastern': 'China Eastern',
    'thai airways': 'Thai Airways',
    'malaysia airlines': 'Malaysia Airlines',
    'vueling': 'Vueling', 'vueling airlines': 'Vueling',
    'norwegian': 'Norwegian', 'norwegian air shuttle': 'Norwegian', 'norwegian air': 'Norwegian',
    'transavia': 'Transavia', 'transavia france': 'Transavia',
    'iberia express': 'Iberia Express',
    'condor': 'Condor', 'condor flugdienst': 'Condor',
    'tui airways': 'TUI Airways', 'tui fly': 'TUI Airways', 'tuifly': 'TUI Airways',
    'aegean': 'Aegean Airlines', 'aegean airlines': 'Aegean Airlines',
    'air serbia': 'Air Serbia',
    'pegasus': 'Pegasus Airlines', 'pegasus airlines': 'Pegasus Airlines',
    'sunexpress': 'SunExpress', 'sun express': 'SunExpress',
    'norse atlantic': 'Norse Atlantic', 'norse': 'Norse Atlantic',
    'flydubai': 'flydubai', 'fly dubai': 'flydubai',
    'air arabia': 'Air Arabia',
    'saudia': 'Saudia', 'saudi arabian airlines': 'Saudia',
    'oman air': 'Oman Air',
    'gulf air': 'Gulf Air',
    'egyptair': 'EgyptAir', 'egypt air': 'EgyptAir',
    'royal air maroc': 'Royal Air Maroc', 'ram': 'Royal Air Maroc',
    'royal jordanian': 'Royal Jordanian',
    'air algérie': 'Air Algérie', 'air algerie': 'Air Algérie',
    'air india': 'Air India',
    'asiana': 'Asiana Airlines', 'asiana airlines': 'Asiana Airlines',
    'china airlines': 'China Airlines',
    'eva air': 'EVA Air',
    'vietnam airlines': 'Vietnam Airlines',
    'philippine airlines': 'Philippine Airlines', 'pal': 'Philippine Airlines',
    'garuda': 'Garuda Indonesia', 'garuda indonesia': 'Garuda Indonesia',
    'air astana': 'Air Astana',
    'voepass': 'VOEPASS', 'passaredo': 'VOEPASS',
    'map linhas aéreas': 'MAP Linhas Aéreas', 'map linhas aereas': 'MAP Linhas Aéreas',
    'azul conecta': 'Azul Conecta',
    'latam brasil': 'LATAM Airlines', 'latam airlines brasil': 'LATAM Airlines',
    'sky airline': 'Sky Airline', 'sky': 'Sky Airline',
    'jetsmart': 'JetSmart', 'jetsmart airlines': 'JetSmart',
    'air transat': 'Air Transat', 'transat': 'Air Transat',
    'porter': 'Porter Airlines', 'porter airlines': 'Porter Airlines',
    'hawaiian': 'Hawaiian Airlines', 'hawaiian airlines': 'Hawaiian Airlines',
    'volotea': 'Volotea', 'binter': 'Binter Canarias', 'binter canarias': 'Binter Canarias',
    'smartwings': 'SmartWings',
    'etihad': 'Etihad Airways', 'etihad airways': 'Etihad Airways',
    'rwandair': 'RwandAir', 'rwanda air': 'RwandAir',
    'jetstar': 'Jetstar', 'jetstar airways': 'Jetstar',
    'scoot': 'Scoot', 'scoot airlines': 'Scoot',
    'peach': 'Peach Aviation', 'peach aviation': 'Peach Aviation',
    'airasia': 'AirAsia', 'air asia': 'AirAsia', 'airasia x': 'AirAsia X',
    'indigo': 'IndiGo', 'spicejet': 'SpiceJet',
    'cebu pacific': 'Cebu Pacific', 'cebu': 'Cebu Pacific',
};

export const AIRLINE_CODE_MAP = {
    'LATAM Airlines': 'LA', 'GOL Linhas Aéreas': 'G3', 'Azul Linhas Aéreas': 'AD',
    'Copa Airlines': 'CM', 'Avianca': 'AV',
    'American Airlines': 'AA', 'United Airlines': 'UA', 'Delta Air Lines': 'DL',
    'Air France': 'AF', 'KLM': 'KL', 'Lufthansa': 'LH',
    'TAP Air Portugal': 'TP', 'Iberia': 'IB', 'British Airways': 'BA',
    'Emirates': 'EK', 'Qatar Airways': 'QR', 'Turkish Airlines': 'TK',
    'Swiss': 'LX', 'Austrian Airlines': 'OS', 'Ethiopian Airlines': 'ET',
    'Aeromexico': 'AM', 'Air Europa': 'UX',
    'Singapore Airlines': 'SQ', 'Cathay Pacific': 'CX',
    'Japan Airlines': 'JL', 'ANA': 'NH',
    'Alaska Airlines': 'AS', 'JetBlue': 'B6', 'Virgin Atlantic': 'VS',
    'ITA Airways': 'AZ', 'Aerolíneas Argentinas': 'AR',
    'Wizz Air': 'W6', 'Ryanair': 'FR', 'easyJet': 'U2',
    'SAS': 'SK', 'Finnair': 'AY', 'WestJet': 'WS',
    'Air Canada': 'AC', 'Southwest Airlines': 'WN',
    'Spirit Airlines': 'NK', 'Frontier Airlines': 'F9',
    'South African Airways': 'SA', 'Kenya Airways': 'KQ',
    'Korean Air': 'KE', 'Air China': 'CA',
    'China Southern': 'CZ', 'China Eastern': 'MU',
    'Thai Airways': 'TG', 'Malaysia Airlines': 'MH',
    'Vueling': 'VY', 'Norwegian': 'DY', 'Transavia': 'HV',
    'Iberia Express': 'I2', 'flydubai': 'FZ', 'Air Arabia': 'G9',
    'Condor': 'DE', 'TUI Airways': 'BY', 'Aegean Airlines': 'A3',
    'Air Serbia': 'JU', 'EgyptAir': 'MS', 'Royal Air Maroc': 'AT',
    'Saudia': 'SV', 'Oman Air': 'WY', 'Gulf Air': 'GF',
    'Air India': 'AI', 'Asiana Airlines': 'OZ', 'China Airlines': 'CI',
    'EVA Air': 'BR', 'Vietnam Airlines': 'VN', 'Philippine Airlines': 'PR',
    'Garuda Indonesia': 'GA', 'Royal Jordanian': 'RJ', 'Air Algérie': 'AH',
    'Air Astana': 'KC', 'Pegasus Airlines': 'PC', 'SunExpress': 'XQ',
    'Etihad Airways': 'EY', 'IndiGo': '6E', 'SpiceJet': 'SG',
    'RwandAir': 'WB', 'Jetstar': 'JQ', 'Scoot': 'TR', 'Peach Aviation': 'MM',
    'AirAsia': 'AK', 'AirAsia X': 'D7', 'Cebu Pacific': '5J',
    'Volotea': 'V7', 'Binter Canarias': 'NT', 'SmartWings': 'QS',
    'Norse Atlantic': 'NO', 'VOEPASS': 'ZP', 'MAP Linhas Aéreas': '8I',
    'Sky Airline': 'H2', 'JetSmart': 'JA', 'Air Transat': 'TS',
    'Porter Airlines': 'PD', 'Hawaiian Airlines': 'HA',
    'Azul Conecta': 'QW', 'Múltiplas companhias': 'XX',
};

export const IATA_TO_AIRLINE = {
    'LA': 'LATAM Airlines', 'JJ': 'LATAM Airlines',
    'G3': 'GOL Linhas Aéreas', 'AD': 'Azul Linhas Aéreas', 'QW': 'Azul Conecta',
    'ZP': 'VOEPASS', '8I': 'MAP Linhas Aéreas',
    'CM': 'Copa Airlines', 'AV': 'Avianca',
    'AA': 'American Airlines', 'UA': 'United Airlines', 'DL': 'Delta Air Lines',
    'WN': 'Southwest Airlines', 'B6': 'JetBlue', 'AS': 'Alaska Airlines',
    'NK': 'Spirit Airlines', 'F9': 'Frontier Airlines', 'HA': 'Hawaiian Airlines',
    'SY': 'Sun Country Airlines',
    'AF': 'Air France', 'KL': 'KLM', 'LH': 'Lufthansa',
    'TP': 'TAP Air Portugal', 'IB': 'Iberia', 'BA': 'British Airways',
    'EK': 'Emirates', 'QR': 'Qatar Airways', 'TK': 'Turkish Airlines',
    'LX': 'Swiss', 'OS': 'Austrian Airlines', 'AY': 'Finnair',
    'SK': 'SAS', 'FR': 'Ryanair', 'U2': 'easyJet', 'W6': 'Wizz Air',
    'VY': 'Vueling', 'DY': 'Norwegian', 'HV': 'Transavia', 'TO': 'Transavia France',
    'I2': 'Iberia Express', 'DE': 'Condor', 'BY': 'TUI Airways',
    'A3': 'Aegean Airlines', 'JU': 'Air Serbia', 'OA': 'Olympic Air',
    'PC': 'Pegasus Airlines', 'XQ': 'SunExpress', 'V7': 'Volotea',
    'NT': 'Binter Canarias', 'QS': 'SmartWings', 'NO': 'Norse Atlantic',
    'ET': 'Ethiopian Airlines', 'WB': 'RwandAir', 'KQ': 'Kenya Airways',
    'SA': 'South African Airways',
    'AM': 'Aeromexico', 'UX': 'Air Europa', 'AR': 'Aerolíneas Argentinas',
    'AC': 'Air Canada', 'WS': 'WestJet', 'PD': 'Porter Airlines',
    'TS': 'Air Transat', 'H2': 'Sky Airline', 'JA': 'JetSmart',
    'VS': 'Virgin Atlantic', 'AZ': 'ITA Airways',
    'SQ': 'Singapore Airlines', 'CX': 'Cathay Pacific',
    'JL': 'Japan Airlines', 'NH': 'ANA', 'KE': 'Korean Air',
    'CA': 'Air China', 'CZ': 'China Southern', 'MU': 'China Eastern',
    'TG': 'Thai Airways', 'MH': 'Malaysia Airlines',
    'OZ': 'Asiana Airlines', 'CI': 'China Airlines', 'BR': 'EVA Air',
    'VN': 'Vietnam Airlines', 'PR': 'Philippine Airlines', 'GA': 'Garuda Indonesia',
    'JQ': 'Jetstar', 'TR': 'Scoot', 'MM': 'Peach Aviation',
    'AK': 'AirAsia', 'FD': 'Thai AirAsia', 'QZ': 'AirAsia Indonesia',
    'D7': 'AirAsia X', '5J': 'Cebu Pacific', '3K': 'Jetstar Asia',
    'FZ': 'flydubai', 'G9': 'Air Arabia', 'EY': 'Etihad Airways',
    'MS': 'EgyptAir', 'AT': 'Royal Air Maroc', 'SV': 'Saudia',
    'WY': 'Oman Air', 'GF': 'Gulf Air', 'RJ': 'Royal Jordanian',
    'AH': 'Air Algérie', 'KC': 'Air Astana',
    'AI': 'Air India', '6E': 'IndiGo', 'SG': 'SpiceJet',
    'PS': 'Ukraine International',
};

export const IATA_CITY_NAMES = {
    ATL: 'Atlanta', LAX: 'Los Angeles', ORD: 'Chicago', DFW: 'Dallas',
    JFK: 'Nova York', EWR: 'Newark', LGA: 'Nova York', MIA: 'Miami',
    SFO: 'São Francisco', SEA: 'Seattle', BOS: 'Boston', DEN: 'Denver',
    IAD: 'Washington D.C.', DCA: 'Washington D.C.', CLT: 'Charlotte',
    PHX: 'Phoenix', MSP: 'Minneapolis', DTW: 'Detroit', PHL: 'Filadélfia',
    LAS: 'Las Vegas', MCO: 'Orlando', IAH: 'Houston', HOU: 'Houston',
    MDW: 'Chicago', FLL: 'Fort Lauderdale', TPA: 'Tampa', SAN: 'San Diego',
    YYZ: 'Toronto', YUL: 'Montreal', YVR: 'Vancouver', YYC: 'Calgary',
    MEX: 'Cidade do México', GDL: 'Guadalajara', MTY: 'Monterrey',
    CUN: 'Cancún', SJO: 'San José', GUA: 'Guatemala',
    PTY: 'Cidade do Panamá', BOG: 'Bogotá', MDE: 'Medellín', CLO: 'Cali',
    CTG: 'Cartagena', LIM: 'Lima', SCL: 'Santiago', EZE: 'Buenos Aires',
    AEP: 'Buenos Aires', UIO: 'Quito', GYE: 'Guayaquil', CCS: 'Caracas',
    MVD: 'Montevidéu', ASU: 'Assunção', LPB: 'La Paz', CBB: 'Cochabamba',
    GRU: 'São Paulo', CGH: 'São Paulo', VCP: 'Campinas',
    GIG: 'Rio de Janeiro', SDU: 'Rio de Janeiro',
    BSB: 'Brasília', CNF: 'Belo Horizonte', SSA: 'Salvador',
    REC: 'Recife', FOR: 'Fortaleza', BEL: 'Belém', MAO: 'Manaus',
    CWB: 'Curitiba', POA: 'Porto Alegre', FLN: 'Florianópolis',
    NAT: 'Natal', MCZ: 'Maceió', AJU: 'Aracaju', THE: 'Teresina',
    SLZ: 'São Luís', CGB: 'Cuiabá', CGR: 'Campo Grande', PMW: 'Palmas',
    PVH: 'Porto Velho', RBR: 'Rio Branco', MCP: 'Macapá',
    LHR: 'Londres', LGW: 'Londres', STN: 'Londres', LTN: 'Londres',
    CDG: 'Paris', ORY: 'Paris', AMS: 'Amsterdã', FRA: 'Frankfurt',
    MUC: 'Munique', MAD: 'Madri', BCN: 'Barcelona', FCO: 'Roma',
    MXP: 'Milão', LIN: 'Milão', ZRH: 'Zurique', GVA: 'Genebra',
    VIE: 'Viena', BRU: 'Bruxelas', LIS: 'Lisboa', OPO: 'Porto',
    DUB: 'Dublin', CPH: 'Copenhague', ARN: 'Estocolmo', OSL: 'Oslo',
    HEL: 'Helsinki', WAW: 'Varsóvia', PRG: 'Praga', BUD: 'Budapeste',
    ATH: 'Atenas', IST: 'Istambul', SAW: 'Istambul',
    DXB: 'Dubai', DOH: 'Doha', AUH: 'Abu Dhabi', RUH: 'Riade',
    AMM: 'Amã', CAI: 'Cairo', JNB: 'Joanesburgo', CPT: 'Cidade do Cabo',
    NBO: 'Nairóbi', ADD: 'Adis Abeba', LOS: 'Lagos', ACC: 'Acra',
    SIN: 'Singapura', KUL: 'Kuala Lumpur', BKK: 'Bangkok',
    HKG: 'Hong Kong', PEK: 'Pequim', PVG: 'Xangai', CAN: 'Guangzhou',
    ICN: 'Seul', NRT: 'Tóquio', HND: 'Tóquio', SYD: 'Sydney',
    MEL: 'Melbourne', AKL: 'Auckland', DEL: 'Nova Délhi', BOM: 'Mumbai',
};

export function normalizeAirline(raw) {
    if (!raw) return '';
    const key = raw.toLowerCase().trim().replace(/\s+/g, ' ');
    if (AIRLINE_NAME_MAP[key]) return AIRLINE_NAME_MAP[key];

    const codeshareMatch = raw.match(/^([A-Za-zÀ-ÿ][A-Za-zÀ-ÿ\s]+?)\s+e\s+/i)
        || raw.match(/^([A-Za-zÀ-ÿ][A-Za-zÀ-ÿ\s]+?)\s+(?:and|&)\s+/i);
    if (codeshareMatch) {
        const first = normalizeAirline(codeshareMatch[1].trim());
        if (first && first !== 'Companhia aérea') return first;
    }

    const camelMatch = raw.match(/^([A-Z][a-z]+)([A-Z])/);
    if (camelMatch) {
        const first = normalizeAirline(camelMatch[1]);
        if (first && first !== 'Companhia aérea') return first;
    }

    return raw.trim();
}

export function iataToCity(code) {
    if (!code) return code;
    return code.split(/\s*·\s*/).map(c => {
        const up = c.trim().toUpperCase();
        return IATA_CITY_NAMES[up] || c.trim();
    }).join(' · ');
}
